//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategorieDeProjet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategorieDeProjet()
        {
            this.Specialisation_ProjetPrincipal = new HashSet<Specialisation_ProjetPrincipal>();
            this.Specialisation_ProjetSecondaire = new HashSet<Specialisation_ProjetSecondaire>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Restriction { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specialisation_ProjetPrincipal> Specialisation_ProjetPrincipal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specialisation_ProjetSecondaire> Specialisation_ProjetSecondaire { get; set; }
    }
}
