//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notation
    {
        public int Id { get; set; }
        public Nullable<int> IdUtilisateur { get; set; }
        public Nullable<int> IdProjet { get; set; }
        public bool Note { get; set; }
    
        public virtual Projet Projet { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
