//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projet()
        {
            this.Dons = new HashSet<Dons>();
            this.Montant = new HashSet<Montant>();
            this.Notation = new HashSet<Notation>();
            this.Specialisation_ProjetPrincipal = new HashSet<Specialisation_ProjetPrincipal>();
            this.Specialisation_ProjetSecondaire = new HashSet<Specialisation_ProjetSecondaire>();
        }
    
        public int Id { get; set; }
        public string Titre { get; set; }
        public string Sous_Titre { get; set; }
        public string Resume { get; set; }
        public byte[] Fichier { get; set; }
        public byte[] Image { get; set; }
        public int RecolteDesire { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public Nullable<int> IdUtilisateur { get; set; }
        public Nullable<int> IdTypeProjet { get; set; }
        public Nullable<bool> Historique { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dons> Dons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Montant> Montant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notation> Notation { get; set; }
        public virtual TypeDeProjet TypeDeProjet { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specialisation_ProjetPrincipal> Specialisation_ProjetPrincipal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specialisation_ProjetSecondaire> Specialisation_ProjetSecondaire { get; set; }
    }
}
