//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAllUtilisateur
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Pseudo { get; set; }
        public string Password { get; set; }
        public System.DateTime DateDeNaissance { get; set; }
        public string Adresse { get; set; }
        public string Pays { get; set; }
        public string Email { get; set; }
        public string Compte_bancaire { get; set; }
        public string Statut { get; set; }
    }
}
