//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAll_Projet
    {
        public int Id { get; set; }
        public string Titre { get; set; }
        public string Sous_Titre { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Pseudo { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public Nullable<bool> Historique { get; set; }
        public string Statut { get; set; }
        public Nullable<int> J_aime { get; set; }
        public Nullable<int> Je_n_aime_Pas { get; set; }
        public Nullable<int> Total_Dons { get; set; }
        public Nullable<int> Total_Crownfunding { get; set; }
    }
}
